# Generated by Django 3.2.3 on 2021-05-21 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210521_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='user-id'),
            preserve_default=False,
        ),
    ]
