# Generated by Django 3.2.3 on 2021-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_log_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log',
            field=models.FileField(null=True, upload_to='', verbose_name='log'),
        ),
    ]
