# Generated by Django 3.2.3 on 2021-05-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_log_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log',
            field=models.CharField(max_length=1000, null=True, verbose_name='log'),
        ),
    ]
