# Generated by Django 3.2.3 on 2021-05-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_log_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='log',
        ),
    ]
