# Generated by Django 3.2.1 on 2021-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_log_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.CharField(max_length=20, verbose_name='user_id'),
        ),
        migrations.AlterField(
            model_name='log',
            name='xes_file',
            field=models.FileField(help_text='Выберите файл', upload_to='logs', verbose_name='xes_file'),
        ),
    ]
